# Generated by Django 4.1.1 on 2022-09-28 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custommodel',
            options={},
        ),
        migrations.AlterModelTable(
            name='custommodel',
            table='custom_user',
        ),
    ]
